name: "Build Stream Deck Plugin"  # If you change this name, you'll also need to update the release.yaml job

on:
  workflow_dispatch:
  pull_request:
    paths:
      - streamdeck-plugin/**
      - com.chrisregado.googlemeet.sdPlugin/**
      - .github/workflows/**
  push:
    paths:
      - streamdeck-plugin/**
      - com.chrisregado.googlemeet.sdPlugin/**
      - .github/workflows/**
    branches:
      - '**'
    tags:
      # Only run on release tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-plugin:
    strategy:
      matrix:
        include:
          - os: macos
            runs_on: macos-latest
          - os: windows
            runs_on: windows-latest
    name: Build ${{ matrix.os }} Stream Deck Plugin
    # Since we run on both branch pushes and PRs, don't do a duplicated run if the PR is for a branch in the local repo:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ${{ matrix.runs_on }}
    defaults:
      run:
        shell: bash
        working-directory: streamdeck-plugin
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up Pip
        run: python -m pip install --upgrade pip

      - name: pip install
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m unittest

      - name: Bundle plugin
        run: pyinstaller --clean --dist ../com.chrisregado.googlemeet.sdPlugin/dist/${{ matrix.os }} src/main.py && rm -rf build

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-plugin-intermediate-build
          path: ${{ github.workspace }}/com.chrisregado.googlemeet.sdPlugin/dist/${{ matrix.os }}

  bundle-streamdeck-distributable:
    name: Bundle multi-OS Stream Deck plugin distributable binary
    runs-on: macos-latest
    needs: [build-plugin]
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # See https://docs.elgato.com/streamdeck/cli/intro/ for supported Node.js versions
          node-version: '22'

      - name: Install Elgato streamdeck CLI tool
        run: npm install -g @elgato/cli@1.5.0

      - name: Download macOS plugin artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-plugin-intermediate-build
          path: com.chrisregado.googlemeet.sdPlugin/dist/macos

      - name: Download Windows plugin artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-plugin-intermediate-build
          path: com.chrisregado.googlemeet.sdPlugin/dist/windows

      - name: Run Elgato linter
        run: streamdeck validate --no-update-check com.chrisregado.googlemeet.sdPlugin

      - name: Make output dir
        run: mkdir ./build

      - name: Bundle plugin
        if: ${{ github.ref_type != 'tag' }}
        run: streamdeck pack --output ./build/ --no-update-check com.chrisregado.googlemeet.sdPlugin

      - name: Bundle plugin using version from git tag
        if: ${{ github.ref_type == 'tag' }}
        run: |
          GIT_TAG="${{ github.ref_name }}"
          VERSION_NUMBER="${GIT_TAG#v}"
          streamdeck pack --output ./build/ --no-update-check --force --version "${VERSION_NUMBER}" com.chrisregado.googlemeet.sdPlugin

      - name: Upload final plugin binary
        uses: actions/upload-artifact@v4
        with:
          name: com.chrisregado.googlemeet.streamDeckPlugin
          path: ./build/com.chrisregado.googlemeet.streamDeckPlugin
